timeout: 1200s
steps:
  - id: "cloud functions install"
    name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    waitFor: ['-']
    dir: 'functions'

  - id: "cloud functions deploy - slackRelay"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'slackRelay', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=slackRelay', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - updateEmailSegmentIndex"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'updateEmailSegmentIndex', '--source=.', '--trigger-event=providers/cloud.firestore/eventTypes/document.write', '--trigger-resource=projects/the-faithful/databases/(default)/documents/email/{email}/{collection}/{docId}', '--runtime', 'nodejs14', '--entry-point=updateEmailSegmentIndex', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  # - id: "cloud functions deploy - transcoderIn"
  #   name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['functions', 'deploy', 'transcoderIn', '--source=.', '--trigger-resource', 'video.the-faithful.com', '--trigger-event', 'google.storage.object.finalize', '--runtime', 'nodejs14', '--entry-point=transcoderIn', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA},COMMIT_SHA=${SHORT_SHA}"]
  #   waitFor: ["cloud functions install"]
  #   dir: 'functions'

  - id: "cloud functions deploy - stripeWebhook"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'stripeWebhook', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=stripeWebhook', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - stripeCheckoutSession"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'stripeCheckoutSession', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=stripeCheckoutSession', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - stripeCheckoutSuccess"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'stripeCheckoutSuccess', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=stripeCheckoutSuccess', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - userEntitlements"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'userEntitlements', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=userEntitlements', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - oauthAuthorize"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'oauthAuthorize', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=oauthAuthorize', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - webhookMailgun"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'webhookMailgun', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=webhookMailgun', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - apiEmail"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'apiEmail', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=apiEmail', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - eventsIn"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'eventsIn', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=eventsIn', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - apiImage"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'apiImage', '--source=.', '--trigger-http', '--runtime', 'nodejs14', '--entry-point=apiImage', '--allow-unauthenticated', '--region', "${_REGION}", '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - eventsFirehosePubSub"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'eventsFirehosePubSub', '--source=.', '--trigger-topic', 'events', '--runtime', 'nodejs14', '--entry-point=eventsFirehosePubSub', '--allow-unauthenticated', '--region', "${_REGION}", '--retry', '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "cloud functions deploy - sendEmailPubSub"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'sendEmailPubSub', '--source=.', '--trigger-topic', 'send-email', '--runtime', 'nodejs14', '--entry-point=sendEmailPubSub', '--allow-unauthenticated', '--region', "${_REGION}", '--retry', '--memory=512', "--set-env-vars", "GCLOUD_PROJECT=${PROJECT_ID},COMMIT_SHA=${SHORT_SHA}"]
    waitFor: ["cloud functions install"]
    dir: 'functions'

  - id: "build image - ssr"
    name: 'gcr.io/kaniko-project/executor:latest'
    waitFor: ['-']
    args: ["--destination=gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",'--cache=false','--cache-ttl=4h', '--build-arg', "COMMIT_SHA=${SHORT_SHA}"]
 
  - id: "build image - ingress"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ['-']
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-ingress", "infra/ingress"]

  - id: "build image - tracking-proxy"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ['-']
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-tracking-proxy", "infra/tracking-proxy"]

  - id: "push image - ingress"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ['build image - ingress']
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-ingress"]

  - id: "push image - tracking-proxy"
    name: "gcr.io/cloud-builders/docker"
    waitFor: ['build image - tracking-proxy']
    args: ["push", "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-tracking-proxy"]

  - id: "deploy prod service"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    waitFor: ['build image - ssr']
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--allow-unauthenticated",
        "--image",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}",
      ]

  # Force the new revision to serve 100% of traffic.
  - id: "ensure prod service live"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    waitFor: ['deploy prod service']
    args:
      [
        "run",
        "services",
        "update-traffic",
        "${_SERVICE_NAME}",
        "--to-latest",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
      ]

  - id: "deploy prod service - ingress"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    waitFor: ['push image - ingress']
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}-ingress",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
        "--allow-unauthenticated",
        "--image",
        "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-ingress",
      ]

  # Force the new revision to serve 100% of traffic.
  - id: "ensure prod service live - ingress"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    waitFor: ['deploy prod service - ingress']
    args:
      [
        "run",
        "services",
        "update-traffic",
        "${_SERVICE_NAME}-ingress",
        "--to-latest",
        "--platform",
        "managed",
        "--region",
        "${_REGION}",
      ]

substitutions:
  _SERVICE_NAME: the-faithful-ssr
  _REGION: us-central1
